/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryPhoto = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'blob' : ExternalBlob,
  'date' : IDL.Text,
  'caption' : IDL.Text,
});
export const AppUserRole = IDL.Variant({
  'admin' : IDL.Null,
  'moderator' : IDL.Null,
  'editor' : IDL.Null,
  'photographer' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Community = IDL.Record({
  'id' : IDL.Text,
  'meetingDay' : IDL.Text,
  'meetingPlace' : IDL.Text,
  'caretaker' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'meetingTime' : IDL.Text,
  'heroImage' : ExternalBlob,
  'shortDescription' : IDL.Text,
  'contactEmail' : IDL.Text,
  'fullDescription' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
  'contactPhone' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'date' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'pinned' : IDL.Bool,
  'liturgicalColor' : IDL.Text,
  'image' : ExternalBlob,
});
export const GalleryAlbum = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'layout' : IDL.Text,
  'description' : IDL.Text,
  'coverImage' : ExternalBlob,
  'photos' : IDL.Vec(GalleryPhoto),
});
export const NewsArticle = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'date' : IDL.Text,
  'published' : IDL.Bool,
  'image' : ExternalBlob,
});
export const ContentBlock = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(AppUserRole),
});
export const LiturgyEntry = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : IDL.Text,
  'entryType' : IDL.Text,
  'order' : IDL.Nat,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'intention' : IDL.Text,
});
export const LiturgyDay = IDL.Record({
  'entries' : IDL.Vec(LiturgyEntry),
  'dayIndex' : IDL.Nat,
});
export const LiturgyWeek = IDL.Record({
  'id' : IDL.Text,
  'weekEnd' : IDL.Text,
  'heroDescription' : IDL.Text,
  'days' : IDL.Vec(LiturgyDay),
  'heroSubtitle' : IDL.Text,
  'heroTitle' : IDL.Text,
  'weekStart' : IDL.Text,
});
export const HomeSection = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'sectionType' : IDL.Text,
  'enabled' : IDL.Bool,
  'customTitle' : IDL.Text,
  'customContent' : IDL.Text,
});
export const MassIntention = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'assignedDayIndex' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'color' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'assignedWeekId' : IDL.Opt(IDL.Text),
  'assignedEntryId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'assignedMassDate' : IDL.Opt(IDL.Text),
  'assignedMassTime' : IDL.Opt(IDL.Text),
  'offeringStatus' : IDL.Text,
  'intention' : IDL.Text,
});
export const ModlitwaConfig = IDL.Record({
  'heroDescription' : IDL.Text,
  'thankYouTitle' : IDL.Text,
  'heroSubtitle' : IDL.Text,
  'accountNumber' : IDL.Text,
  'heroTitle' : IDL.Text,
  'bankOwner' : IDL.Text,
  'thankYouText' : IDL.Text,
});
export const PrayerStar = IDL.Record({
  'id' : IDL.Text,
  'isApproved' : IDL.Bool,
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'color' : IDL.Text,
  'joinedAt' : IDL.Text,
  'isHidden' : IDL.Bool,
  'isPublic' : IDL.Bool,
  'prayCount' : IDL.Nat,
  'intention' : IDL.Opt(IDL.Text),
});
export const ShopOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'trackingNumber' : IDL.Text,
  'paymentConfirmed' : IDL.Bool,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'createdAt' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'deliveryType' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'adminNotes' : IDL.Text,
  'productPrice' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'contactData' : IDL.Text,
  'navigation' : IDL.Text,
  'aestheticMode' : IDL.Text,
  'typography' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCommunityPhoto' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'addPhoto' : IDL.Func([IDL.Text, GalleryPhoto], [], []),
  'assignAppRole' : IDL.Func([IDL.Principal, AppUserRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'copyPreviousWeek' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createCommunity' : IDL.Func([Community], [], []),
  'createEvent' : IDL.Func([Event], [], []),
  'createGalleryAlbum' : IDL.Func([GalleryAlbum], [], []),
  'createNewsArticle' : IDL.Func([NewsArticle], [], []),
  'deleteCommunity' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryAlbum' : IDL.Func([IDL.Text], [], []),
  'deleteLiturgyWeek' : IDL.Func([IDL.Text], [], []),
  'deleteMassIntention' : IDL.Func([IDL.Text], [], []),
  'deleteNewsArticle' : IDL.Func([IDL.Text], [], []),
  'deletePrayerStar' : IDL.Func([IDL.Text], [], []),
  'deleteShopOrder' : IDL.Func([IDL.Text], [], []),
  'getAllCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
  'getAllContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAppRole' : IDL.Func([IDL.Principal], [IDL.Opt(AppUserRole)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunity' : IDL.Func([IDL.Text], [IDL.Opt(Community)], ['query']),
  'getContentBlock' : IDL.Func([IDL.Text], [IDL.Opt(ContentBlock)], ['query']),
  'getCurrentLiturgyWeek' : IDL.Func([], [IDL.Opt(LiturgyWeek)], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getGalleryAlbum' : IDL.Func([IDL.Text], [IDL.Opt(GalleryAlbum)], ['query']),
  'getGalleryAlbums' : IDL.Func([], [IDL.Vec(GalleryAlbum)], ['query']),
  'getHomeSections' : IDL.Func([], [IDL.Vec(HomeSection)], ['query']),
  'getLiturgyWeek' : IDL.Func([IDL.Text], [IDL.Opt(LiturgyWeek)], ['query']),
  'getMassIntentions' : IDL.Func([], [IDL.Vec(MassIntention)], ['query']),
  'getModlitwaConfig' : IDL.Func([], [IDL.Opt(ModlitwaConfig)], ['query']),
  'getNewOrdersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getNewsArticle' : IDL.Func([IDL.Text], [IDL.Opt(NewsArticle)], ['query']),
  'getPhotosByAlbum' : IDL.Func([IDL.Text], [IDL.Vec(GalleryPhoto)], ['query']),
  'getPrayerStars' : IDL.Func([], [IDL.Vec(PrayerStar)], ['query']),
  'getPublicEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPublicNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
  'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllRoles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, AppUserRole))],
      ['query'],
    ),
  'listLiturgyWeeks' : IDL.Func([], [IDL.Vec(LiturgyWeek)], ['query']),
  'removeCommunityPhoto' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removePhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLiturgyWeek' : IDL.Func([LiturgyWeek], [], []),
  'saveMassIntention' : IDL.Func([MassIntention], [], []),
  'saveModlitwaConfig' : IDL.Func([ModlitwaConfig], [], []),
  'savePrayerStar' : IDL.Func([PrayerStar], [], []),
  'saveShopOrder' : IDL.Func([ShopOrder], [], []),
  'setCurrentLiturgyWeekId' : IDL.Func([IDL.Text], [], []),
  'updateCommunity' : IDL.Func([IDL.Text, Community], [], []),
  'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateEvent' : IDL.Func([IDL.Text, Event], [], []),
  'updateGalleryAlbum' : IDL.Func([IDL.Text, GalleryAlbum], [], []),
  'updateHomeSections' : IDL.Func([IDL.Vec(HomeSection)], [], []),
  'updateNewsArticle' : IDL.Func([IDL.Text, NewsArticle], [], []),
  'updateShopOrder' : IDL.Func([IDL.Text, ShopOrder], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryPhoto = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'blob' : ExternalBlob,
    'date' : IDL.Text,
    'caption' : IDL.Text,
  });
  const AppUserRole = IDL.Variant({
    'admin' : IDL.Null,
    'moderator' : IDL.Null,
    'editor' : IDL.Null,
    'photographer' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Community = IDL.Record({
    'id' : IDL.Text,
    'meetingDay' : IDL.Text,
    'meetingPlace' : IDL.Text,
    'caretaker' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'meetingTime' : IDL.Text,
    'heroImage' : ExternalBlob,
    'shortDescription' : IDL.Text,
    'contactEmail' : IDL.Text,
    'fullDescription' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
    'contactPhone' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'date' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'pinned' : IDL.Bool,
    'liturgicalColor' : IDL.Text,
    'image' : ExternalBlob,
  });
  const GalleryAlbum = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'layout' : IDL.Text,
    'description' : IDL.Text,
    'coverImage' : ExternalBlob,
    'photos' : IDL.Vec(GalleryPhoto),
  });
  const NewsArticle = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'date' : IDL.Text,
    'published' : IDL.Bool,
    'image' : ExternalBlob,
  });
  const ContentBlock = IDL.Record({ 'id' : IDL.Text, 'content' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(AppUserRole),
  });
  const LiturgyEntry = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : IDL.Text,
    'entryType' : IDL.Text,
    'order' : IDL.Nat,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'intention' : IDL.Text,
  });
  const LiturgyDay = IDL.Record({
    'entries' : IDL.Vec(LiturgyEntry),
    'dayIndex' : IDL.Nat,
  });
  const LiturgyWeek = IDL.Record({
    'id' : IDL.Text,
    'weekEnd' : IDL.Text,
    'heroDescription' : IDL.Text,
    'days' : IDL.Vec(LiturgyDay),
    'heroSubtitle' : IDL.Text,
    'heroTitle' : IDL.Text,
    'weekStart' : IDL.Text,
  });
  const HomeSection = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'sectionType' : IDL.Text,
    'enabled' : IDL.Bool,
    'customTitle' : IDL.Text,
    'customContent' : IDL.Text,
  });
  const MassIntention = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'assignedDayIndex' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'color' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'assignedWeekId' : IDL.Opt(IDL.Text),
    'assignedEntryId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'assignedMassDate' : IDL.Opt(IDL.Text),
    'assignedMassTime' : IDL.Opt(IDL.Text),
    'offeringStatus' : IDL.Text,
    'intention' : IDL.Text,
  });
  const ModlitwaConfig = IDL.Record({
    'heroDescription' : IDL.Text,
    'thankYouTitle' : IDL.Text,
    'heroSubtitle' : IDL.Text,
    'accountNumber' : IDL.Text,
    'heroTitle' : IDL.Text,
    'bankOwner' : IDL.Text,
    'thankYouText' : IDL.Text,
  });
  const PrayerStar = IDL.Record({
    'id' : IDL.Text,
    'isApproved' : IDL.Bool,
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'color' : IDL.Text,
    'joinedAt' : IDL.Text,
    'isHidden' : IDL.Bool,
    'isPublic' : IDL.Bool,
    'prayCount' : IDL.Nat,
    'intention' : IDL.Opt(IDL.Text),
  });
  const ShopOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'trackingNumber' : IDL.Text,
    'paymentConfirmed' : IDL.Bool,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'createdAt' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'deliveryType' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'adminNotes' : IDL.Text,
    'productPrice' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'contactData' : IDL.Text,
    'navigation' : IDL.Text,
    'aestheticMode' : IDL.Text,
    'typography' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCommunityPhoto' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'addPhoto' : IDL.Func([IDL.Text, GalleryPhoto], [], []),
    'assignAppRole' : IDL.Func([IDL.Principal, AppUserRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'copyPreviousWeek' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createCommunity' : IDL.Func([Community], [], []),
    'createEvent' : IDL.Func([Event], [], []),
    'createGalleryAlbum' : IDL.Func([GalleryAlbum], [], []),
    'createNewsArticle' : IDL.Func([NewsArticle], [], []),
    'deleteCommunity' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryAlbum' : IDL.Func([IDL.Text], [], []),
    'deleteLiturgyWeek' : IDL.Func([IDL.Text], [], []),
    'deleteMassIntention' : IDL.Func([IDL.Text], [], []),
    'deleteNewsArticle' : IDL.Func([IDL.Text], [], []),
    'deletePrayerStar' : IDL.Func([IDL.Text], [], []),
    'deleteShopOrder' : IDL.Func([IDL.Text], [], []),
    'getAllCommunities' : IDL.Func([], [IDL.Vec(Community)], ['query']),
    'getAllContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAppRole' : IDL.Func([IDL.Principal], [IDL.Opt(AppUserRole)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunity' : IDL.Func([IDL.Text], [IDL.Opt(Community)], ['query']),
    'getContentBlock' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContentBlock)],
        ['query'],
      ),
    'getCurrentLiturgyWeek' : IDL.Func([], [IDL.Opt(LiturgyWeek)], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getGalleryAlbum' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GalleryAlbum)],
        ['query'],
      ),
    'getGalleryAlbums' : IDL.Func([], [IDL.Vec(GalleryAlbum)], ['query']),
    'getHomeSections' : IDL.Func([], [IDL.Vec(HomeSection)], ['query']),
    'getLiturgyWeek' : IDL.Func([IDL.Text], [IDL.Opt(LiturgyWeek)], ['query']),
    'getMassIntentions' : IDL.Func([], [IDL.Vec(MassIntention)], ['query']),
    'getModlitwaConfig' : IDL.Func([], [IDL.Opt(ModlitwaConfig)], ['query']),
    'getNewOrdersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getNewsArticle' : IDL.Func([IDL.Text], [IDL.Opt(NewsArticle)], ['query']),
    'getPhotosByAlbum' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryPhoto)],
        ['query'],
      ),
    'getPrayerStars' : IDL.Func([], [IDL.Vec(PrayerStar)], ['query']),
    'getPublicEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPublicNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
    'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllRoles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, AppUserRole))],
        ['query'],
      ),
    'listLiturgyWeeks' : IDL.Func([], [IDL.Vec(LiturgyWeek)], ['query']),
    'removeCommunityPhoto' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removePhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLiturgyWeek' : IDL.Func([LiturgyWeek], [], []),
    'saveMassIntention' : IDL.Func([MassIntention], [], []),
    'saveModlitwaConfig' : IDL.Func([ModlitwaConfig], [], []),
    'savePrayerStar' : IDL.Func([PrayerStar], [], []),
    'saveShopOrder' : IDL.Func([ShopOrder], [], []),
    'setCurrentLiturgyWeekId' : IDL.Func([IDL.Text], [], []),
    'updateCommunity' : IDL.Func([IDL.Text, Community], [], []),
    'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateEvent' : IDL.Func([IDL.Text, Event], [], []),
    'updateGalleryAlbum' : IDL.Func([IDL.Text, GalleryAlbum], [], []),
    'updateHomeSections' : IDL.Func([IDL.Vec(HomeSection)], [], []),
    'updateNewsArticle' : IDL.Func([IDL.Text, NewsArticle], [], []),
    'updateShopOrder' : IDL.Func([IDL.Text, ShopOrder], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };