/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'admin' : null } |
  { 'moderator' : null } |
  { 'editor' : null } |
  { 'photographer' : null };
export interface Community {
  'id' : string,
  'name' : string,
  'shortDescription' : string,
  'fullDescription' : string,
  'meetingDay' : string,
  'meetingTime' : string,
  'meetingPlace' : string,
  'caretaker' : string,
  'contactPhone' : string,
  'contactEmail' : string,
  'order' : bigint,
  'heroImage' : ExternalBlob,
  'photos' : Array<ExternalBlob>,
}
export interface ContentBlock { 'id' : string, 'content' : string }
export interface Event {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'date' : string,
  'published' : boolean,
  'description' : string,
  'pinned' : boolean,
  'liturgicalColor' : string,
  'image' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface GalleryAlbum {
  'id' : string,
  'date' : string,
  'name' : string,
  'layout' : string,
  'description' : string,
  'coverImage' : ExternalBlob,
  'photos' : Array<GalleryPhoto>,
}
export interface GalleryPhoto {
  'id' : string,
  'order' : bigint,
  'blob' : ExternalBlob,
  'date' : string,
  'caption' : string,
}
export interface HomeSection {
  'id' : string,
  'order' : bigint,
  'sectionType' : string,
  'enabled' : boolean,
  'customTitle' : string,
  'customContent' : string,
}
export interface LiturgyDay {
  'entries' : Array<LiturgyEntry>,
  'dayIndex' : bigint,
}
export interface LiturgyEntry {
  'id' : string,
  'serviceType' : string,
  'entryType' : string,
  'order' : bigint,
  'time' : string,
  'description' : string,
  'intention' : string,
}
export interface LiturgyWeek {
  'id' : string,
  'weekEnd' : string,
  'heroDescription' : string,
  'days' : Array<LiturgyDay>,
  'heroSubtitle' : string,
  'heroTitle' : string,
  'weekStart' : string,
}
export interface NewsArticle {
  'id' : string,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'date' : string,
  'published' : boolean,
  'image' : ExternalBlob,
}
export interface SiteSettings {
  'contactData' : string,
  'navigation' : string,
  'aestheticMode' : string,
  'typography' : string,
}
export interface UserProfile { 'name' : string, 'role' : [] | [AppUserRole] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommunityPhoto' : ActorMethod<[string, Uint8Array], undefined>,
  'addPhoto' : ActorMethod<[string, GalleryPhoto], undefined>,
  'assignAppRole' : ActorMethod<[Principal, AppUserRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'copyPreviousWeek' : ActorMethod<[string, string, string, string], undefined>,
  'createCommunity' : ActorMethod<[Community], undefined>,
  'createEvent' : ActorMethod<[Event], undefined>,
  'createGalleryAlbum' : ActorMethod<[GalleryAlbum], undefined>,
  'createNewsArticle' : ActorMethod<[NewsArticle], undefined>,
  'deleteCommunity' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteGalleryAlbum' : ActorMethod<[string], undefined>,
  'deleteLiturgyWeek' : ActorMethod<[string], undefined>,
  'deleteNewsArticle' : ActorMethod<[string], undefined>,
  'getAllCommunities' : ActorMethod<[], Array<Community>>,
  'getAllContentBlocks' : ActorMethod<[], Array<ContentBlock>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllNews' : ActorMethod<[], Array<NewsArticle>>,
  'getAppRole' : ActorMethod<[Principal], [] | [AppUserRole]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunity' : ActorMethod<[string], [] | [Community]>,
  'getContentBlock' : ActorMethod<[string], [] | [ContentBlock]>,
  'getCurrentLiturgyWeek' : ActorMethod<[], [] | [LiturgyWeek]>,
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  'getGalleryAlbum' : ActorMethod<[string], [] | [GalleryAlbum]>,
  'getGalleryAlbums' : ActorMethod<[], Array<GalleryAlbum>>,
  'getHomeSections' : ActorMethod<[], Array<HomeSection>>,
  'getLiturgyWeek' : ActorMethod<[string], [] | [LiturgyWeek]>,
  'getNewsArticle' : ActorMethod<[string], [] | [NewsArticle]>,
  'getPhotosByAlbum' : ActorMethod<[string], Array<GalleryPhoto>>,
  'getPublicEvents' : ActorMethod<[], Array<Event>>,
  'getPublicNews' : ActorMethod<[], Array<NewsArticle>>,
  'getSiteSettings' : ActorMethod<[], [] | [SiteSettings]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllRoles' : ActorMethod<[], Array<[Principal, AppUserRole]>>,
  'listLiturgyWeeks' : ActorMethod<[], Array<LiturgyWeek>>,
  'removeCommunityPhoto' : ActorMethod<[string, bigint], undefined>,
  'removePhoto' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLiturgyWeek' : ActorMethod<[LiturgyWeek], undefined>,
  'updateCommunity' : ActorMethod<[string, Community], undefined>,
  'updateContentBlock' : ActorMethod<[string, string], undefined>,
  'updateEvent' : ActorMethod<[string, Event], undefined>,
  'updateGalleryAlbum' : ActorMethod<[string, GalleryAlbum], undefined>,
  'updateHomeSections' : ActorMethod<[Array<HomeSection>], undefined>,
  'updateNewsArticle' : ActorMethod<[string, NewsArticle], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];