/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContentBlock {
    id: string;
    content: string;
}
export interface GalleryPhoto {
    id: string;
    order: bigint;
    blob: ExternalBlob;
    date: string;
    caption: string;
}
export interface LiturgyWeek {
    id: string;
    weekEnd: string;
    heroDescription: string;
    days: Array<LiturgyDay>;
    heroSubtitle: string;
    heroTitle: string;
    weekStart: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    id: string;
    title: string;
    featured: boolean;
    date: string;
    published: boolean;
    description: string;
    pinned: boolean;
    liturgicalColor: string;
    image: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Community {
    id: string;
    meetingDay: string;
    meetingPlace: string;
    caretaker: string;
    order: bigint;
    name: string;
    meetingTime: string;
    heroImage: ExternalBlob;
    shortDescription: string;
    contactEmail: string;
    fullDescription: string;
    photos: Array<ExternalBlob>;
    contactPhone: string;
}
export interface PrayerStar {
    id: string;
    isApproved: boolean;
    city?: string;
    name?: string;
    color: string;
    joinedAt: string;
    isHidden: boolean;
    isPublic: boolean;
    prayCount: bigint;
    intention?: string;
}
export interface SiteSettings {
    contactData: string;
    navigation: string;
    aestheticMode: string;
    typography: string;
}
export interface GalleryAlbum {
    id: string;
    date: string;
    name: string;
    layout: string;
    description: string;
    coverImage: ExternalBlob;
    photos: Array<GalleryPhoto>;
}
export interface ModlitwaConfig {
    heroDescription: string;
    thankYouTitle: string;
    heroSubtitle: string;
    accountNumber: string;
    heroTitle: string;
    bankOwner: string;
    thankYouText: string;
}
export interface NewsArticle {
    id: string;
    title: string;
    content: string;
    order: bigint;
    date: string;
    published: boolean;
    image: ExternalBlob;
}
export interface LiturgyDay {
    entries: Array<LiturgyEntry>;
    dayIndex: bigint;
}
export interface HomeSection {
    id: string;
    order: bigint;
    sectionType: string;
    enabled: boolean;
    customTitle: string;
    customContent: string;
}
export interface LiturgyEntry {
    id: string;
    serviceType: string;
    entryType: string;
    order: bigint;
    time: string;
    description: string;
    intention: string;
}
export interface MassIntention {
    id: string;
    status: string;
    assignedDayIndex?: bigint;
    name: string;
    createdAt: string;
    color: string;
    email?: string;
    assignedWeekId?: string;
    assignedEntryId?: string;
    phone?: string;
    assignedMassDate?: string;
    assignedMassTime?: string;
    offeringStatus: string;
    intention: string;
}
export interface UserProfile {
    name: string;
    role?: AppUserRole;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppUserRole {
    admin = "admin",
    moderator = "moderator",
    editor = "editor",
    photographer = "photographer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCommunityPhoto(communityId: string, photo: ExternalBlob): Promise<void>;
    addPhoto(albumId: string, photo: GalleryPhoto): Promise<void>;
    assignAppRole(user: Principal, role: AppUserRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    copyPreviousWeek(fromWeekId: string, toWeekId: string, newWeekStart: string, newWeekEnd: string): Promise<void>;
    createCommunity(community: Community): Promise<void>;
    createEvent(event: Event): Promise<void>;
    createGalleryAlbum(album: GalleryAlbum): Promise<void>;
    createNewsArticle(article: NewsArticle): Promise<void>;
    deleteCommunity(id: string): Promise<void>;
    deleteEvent(id: string): Promise<void>;
    deleteGalleryAlbum(id: string): Promise<void>;
    deleteLiturgyWeek(weekId: string): Promise<void>;
    deleteMassIntention(id: string): Promise<void>;
    deleteNewsArticle(id: string): Promise<void>;
    deletePrayerStar(id: string): Promise<void>;
    getAllCommunities(): Promise<Array<Community>>;
    getAllContentBlocks(): Promise<Array<ContentBlock>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllNews(): Promise<Array<NewsArticle>>;
    getAppRole(user: Principal): Promise<AppUserRole | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunity(id: string): Promise<Community | null>;
    getContentBlock(key: string): Promise<ContentBlock | null>;
    getCurrentLiturgyWeek(): Promise<LiturgyWeek | null>;
    getEvent(id: string): Promise<Event | null>;
    getGalleryAlbum(id: string): Promise<GalleryAlbum | null>;
    getGalleryAlbums(): Promise<Array<GalleryAlbum>>;
    getHomeSections(): Promise<Array<HomeSection>>;
    getLiturgyWeek(weekId: string): Promise<LiturgyWeek | null>;
    getMassIntentions(): Promise<Array<MassIntention>>;
    getModlitwaConfig(): Promise<ModlitwaConfig | null>;
    getNewsArticle(id: string): Promise<NewsArticle | null>;
    getPhotosByAlbum(albumId: string): Promise<Array<GalleryPhoto>>;
    getPrayerStars(): Promise<Array<PrayerStar>>;
    getPublicEvents(): Promise<Array<Event>>;
    getPublicNews(): Promise<Array<NewsArticle>>;
    getSiteSettings(): Promise<SiteSettings | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllRoles(): Promise<Array<[Principal, AppUserRole]>>;
    listLiturgyWeeks(): Promise<Array<LiturgyWeek>>;
    removeCommunityPhoto(communityId: string, photoIndex: bigint): Promise<void>;
    removePhoto(albumId: string, photoId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveLiturgyWeek(week: LiturgyWeek): Promise<void>;
    setCurrentLiturgyWeekId(weekId: string): Promise<void>;
    saveMassIntention(intention: MassIntention): Promise<void>;
    saveModlitwaConfig(config: ModlitwaConfig): Promise<void>;
    savePrayerStar(star: PrayerStar): Promise<void>;
    updateCommunity(id: string, community: Community): Promise<void>;
    updateContentBlock(key: string, content: string): Promise<void>;
    updateEvent(id: string, event: Event): Promise<void>;
    updateGalleryAlbum(id: string, album: GalleryAlbum): Promise<void>;
    updateHomeSections(sections: Array<HomeSection>): Promise<void>;
    updateNewsArticle(id: string, article: NewsArticle): Promise<void>;
    updateSiteSettings(settings: SiteSettings): Promise<void>;
}
import type { AppUserRole as _AppUserRole, Community as _Community, ContentBlock as _ContentBlock, Event as _Event, ExternalBlob as _ExternalBlob, GalleryAlbum as _GalleryAlbum, GalleryPhoto as _GalleryPhoto, LiturgyWeek as _LiturgyWeek, MassIntention as _MassIntention, ModlitwaConfig as _ModlitwaConfig, NewsArticle as _NewsArticle, PrayerStar as _PrayerStar, SiteSettings as _SiteSettings, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCommunityPhoto(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommunityPhoto(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommunityPhoto(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPhoto(arg0: string, arg1: GalleryPhoto): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhoto(arg0, await to_candid_GalleryPhoto_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhoto(arg0, await to_candid_GalleryPhoto_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignAppRole(arg0: Principal, arg1: AppUserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAppRole(arg0, to_candid_AppUserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAppRole(arg0, to_candid_AppUserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async copyPreviousWeek(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.copyPreviousWeek(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.copyPreviousWeek(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createCommunity(arg0: Community): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommunity(await to_candid_Community_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommunity(await to_candid_Community_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createGalleryAlbum(arg0: GalleryAlbum): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGalleryAlbum(await to_candid_GalleryAlbum_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGalleryAlbum(await to_candid_GalleryAlbum_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNewsArticle(arg0: NewsArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewsArticle(await to_candid_NewsArticle_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewsArticle(await to_candid_NewsArticle_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCommunity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCommunity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCommunity(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteGalleryAlbum(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryAlbum(arg0);
            return result;
        }
    }
    async deleteLiturgyWeek(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLiturgyWeek(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLiturgyWeek(arg0);
            return result;
        }
    }
    async deleteMassIntention(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMassIntention(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMassIntention(arg0);
            return result;
        }
    }
    async deleteNewsArticle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsArticle(arg0);
            return result;
        }
    }
    async deletePrayerStar(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrayerStar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrayerStar(arg0);
            return result;
        }
    }
    async getAllCommunities(): Promise<Array<Community>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommunities();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommunities();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContentBlocks(): Promise<Array<ContentBlock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentBlocks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentBlocks();
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppRole(arg0: Principal): Promise<AppUserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppRole(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppRole(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunity(arg0: string): Promise<Community | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunity(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunity(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentBlock(arg0: string): Promise<ContentBlock | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentBlock(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentBlock(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentLiturgyWeek(): Promise<LiturgyWeek | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentLiturgyWeek();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentLiturgyWeek();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryAlbum(arg0: string): Promise<GalleryAlbum | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryAlbum(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryAlbum(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryAlbums(): Promise<Array<GalleryAlbum>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryAlbums();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryAlbums();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeSections(): Promise<Array<HomeSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeSections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeSections();
            return result;
        }
    }
    async getLiturgyWeek(arg0: string): Promise<LiturgyWeek | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiturgyWeek(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiturgyWeek(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMassIntentions(): Promise<Array<MassIntention>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMassIntentions();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMassIntentions();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModlitwaConfig(): Promise<ModlitwaConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModlitwaConfig();
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModlitwaConfig();
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsArticle(arg0: string): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticle(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticle(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotosByAlbum(arg0: string): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByAlbum(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByAlbum(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrayerStars(): Promise<Array<PrayerStar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrayerStars();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrayerStars();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicEvents();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicEvents();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicNews();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicNews();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteSettings(): Promise<SiteSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllRoles(): Promise<Array<[Principal, AppUserRole]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllRoles();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllRoles();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLiturgyWeeks(): Promise<Array<LiturgyWeek>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLiturgyWeeks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLiturgyWeeks();
            return result;
        }
    }
    async removeCommunityPhoto(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCommunityPhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCommunityPhoto(arg0, arg1);
            return result;
        }
    }
    async removePhoto(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePhoto(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveLiturgyWeek(arg0: LiturgyWeek): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLiturgyWeek(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLiturgyWeek(arg0);
            return result;
        }
    }
    async setCurrentLiturgyWeekId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCurrentLiturgyWeekId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCurrentLiturgyWeekId(arg0);
            return result;
        }
    }
    async saveMassIntention(arg0: MassIntention): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMassIntention(to_candid_MassIntention_n70(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMassIntention(to_candid_MassIntention_n70(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveModlitwaConfig(arg0: ModlitwaConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveModlitwaConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveModlitwaConfig(arg0);
            return result;
        }
    }
    async savePrayerStar(arg0: PrayerStar): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePrayerStar(to_candid_PrayerStar_n72(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePrayerStar(to_candid_PrayerStar_n72(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCommunity(arg0: string, arg1: Community): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCommunity(arg0, await to_candid_Community_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCommunity(arg0, await to_candid_Community_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateContentBlock(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentBlock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentBlock(arg0, arg1);
            return result;
        }
    }
    async updateEvent(arg0: string, arg1: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateGalleryAlbum(arg0: string, arg1: GalleryAlbum): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryAlbum(arg0, await to_candid_GalleryAlbum_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryAlbum(arg0, await to_candid_GalleryAlbum_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHomeSections(arg0: Array<HomeSection>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomeSections(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomeSections(arg0);
            return result;
        }
    }
    async updateNewsArticle(arg0: string, arg1: NewsArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsArticle(arg0, await to_candid_NewsArticle_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsArticle(arg0, await to_candid_NewsArticle_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSiteSettings(arg0: SiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0);
            return result;
        }
    }
}
function from_candid_AppUserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Community_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Community): Promise<Community> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Event_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryAlbum_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryAlbum): Promise<GalleryAlbum> {
    return await from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_GalleryPhoto_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryPhoto): Promise<GalleryPhoto> {
    return await from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_MassIntention_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MassIntention): MassIntention {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function from_candid_NewsArticle_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsArticle): Promise<NewsArticle> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PrayerStar_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrayerStar): PrayerStar {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUserRole]): AppUserRole | null {
    return value.length === 0 ? null : from_candid_AppUserRole_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n40(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Community]): Promise<Community | null> {
    return value.length === 0 ? null : await from_candid_Community_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentBlock]): ContentBlock | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LiturgyWeek]): LiturgyWeek | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Promise<Event | null> {
    return value.length === 0 ? null : await from_candid_Event_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryAlbum]): Promise<GalleryAlbum | null> {
    return value.length === 0 ? null : await from_candid_GalleryAlbum_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ModlitwaConfig]): ModlitwaConfig | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticle]): Promise<NewsArticle | null> {
    return value.length === 0 ? null : await from_candid_NewsArticle_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SiteSettings]): SiteSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    meetingDay: string;
    meetingPlace: string;
    caretaker: string;
    order: bigint;
    name: string;
    meetingTime: string;
    heroImage: _ExternalBlob;
    shortDescription: string;
    contactEmail: string;
    fullDescription: string;
    photos: Array<_ExternalBlob>;
    contactPhone: string;
}): Promise<{
    id: string;
    meetingDay: string;
    meetingPlace: string;
    caretaker: string;
    order: bigint;
    name: string;
    meetingTime: string;
    heroImage: ExternalBlob;
    shortDescription: string;
    contactEmail: string;
    fullDescription: string;
    photos: Array<ExternalBlob>;
    contactPhone: string;
}> {
    return {
        id: value.id,
        meetingDay: value.meetingDay,
        meetingPlace: value.meetingPlace,
        caretaker: value.caretaker,
        order: value.order,
        name: value.name,
        meetingTime: value.meetingTime,
        heroImage: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.heroImage),
        shortDescription: value.shortDescription,
        contactEmail: value.contactEmail,
        fullDescription: value.fullDescription,
        photos: await from_candid_vec_n29(_uploadFile, _downloadFile, value.photos),
        contactPhone: value.contactPhone
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    featured: boolean;
    date: string;
    published: boolean;
    description: string;
    pinned: boolean;
    liturgicalColor: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    featured: boolean;
    date: string;
    published: boolean;
    description: string;
    pinned: boolean;
    liturgicalColor: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        date: value.date,
        published: value.published,
        description: value.description,
        pinned: value.pinned,
        liturgicalColor: value.liturgicalColor,
        image: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    order: bigint;
    date: string;
    published: boolean;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    content: string;
    order: bigint;
    date: string;
    published: boolean;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        order: value.order,
        date: value.date,
        published: value.published,
        image: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: [] | [_AppUserRole];
}): {
    name: string;
    role?: AppUserRole;
} {
    return {
        name: value.name,
        role: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.role))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    name: string;
    layout: string;
    description: string;
    coverImage: _ExternalBlob;
    photos: Array<_GalleryPhoto>;
}): Promise<{
    id: string;
    date: string;
    name: string;
    layout: string;
    description: string;
    coverImage: ExternalBlob;
    photos: Array<GalleryPhoto>;
}> {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        layout: value.layout,
        description: value.description,
        coverImage: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.coverImage),
        photos: await from_candid_vec_n51(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    order: bigint;
    blob: _ExternalBlob;
    date: string;
    caption: string;
}): Promise<{
    id: string;
    order: bigint;
    blob: ExternalBlob;
    date: string;
    caption: string;
}> {
    return {
        id: value.id,
        order: value.order,
        blob: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.blob),
        date: value.date,
        caption: value.caption
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    assignedDayIndex: [] | [bigint];
    name: string;
    createdAt: string;
    color: string;
    email: [] | [string];
    assignedWeekId: [] | [string];
    assignedEntryId: [] | [string];
    phone: [] | [string];
    assignedMassDate: [] | [string];
    assignedMassTime: [] | [string];
    offeringStatus: string;
    intention: string;
}): {
    id: string;
    status: string;
    assignedDayIndex?: bigint;
    name: string;
    createdAt: string;
    color: string;
    email?: string;
    assignedWeekId?: string;
    assignedEntryId?: string;
    phone?: string;
    assignedMassDate?: string;
    assignedMassTime?: string;
    offeringStatus: string;
    intention: string;
} {
    return {
        id: value.id,
        status: value.status,
        assignedDayIndex: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.assignedDayIndex)),
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        email: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.email)),
        assignedWeekId: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.assignedWeekId)),
        assignedEntryId: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.assignedEntryId)),
        phone: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.phone)),
        assignedMassDate: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.assignedMassDate)),
        assignedMassTime: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.assignedMassTime)),
        offeringStatus: value.offeringStatus,
        intention: value.intention
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isApproved: boolean;
    city: [] | [string];
    name: [] | [string];
    color: string;
    joinedAt: string;
    isHidden: boolean;
    isPublic: boolean;
    prayCount: bigint;
    intention: [] | [string];
}): {
    id: string;
    isApproved: boolean;
    city?: string;
    name?: string;
    color: string;
    joinedAt: string;
    isHidden: boolean;
    isPublic: boolean;
    prayCount: bigint;
    intention?: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        city: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.city)),
        name: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.name)),
        color: value.color,
        joinedAt: value.joinedAt,
        isHidden: value.isHidden,
        isPublic: value.isPublic,
        prayCount: value.prayCount,
        intention: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.intention))
    };
}
function from_candid_tuple_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _AppUserRole]): [Principal, AppUserRole] {
    return [
        value[0],
        from_candid_AppUserRole_n37(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    moderator: null;
} | {
    editor: null;
} | {
    photographer: null;
}): AppUserRole {
    return "admin" in value ? AppUserRole.admin : "moderator" in value ? AppUserRole.moderator : "editor" in value ? AppUserRole.editor : "photographer" in value ? AppUserRole.photographer : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Community>): Promise<Array<Community>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Community_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsArticle>): Promise<Array<NewsArticle>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NewsArticle_n34(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryPhoto>): Promise<Array<GalleryPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryPhoto_n52(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryAlbum>): Promise<Array<GalleryAlbum>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryAlbum_n49(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MassIntention>): Array<MassIntention> {
    return value.map((x)=>from_candid_MassIntention_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrayerStar>): Array<PrayerStar> {
    return value.map((x)=>from_candid_PrayerStar_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _AppUserRole]>): Array<[Principal, AppUserRole]> {
    return value.map((x)=>from_candid_tuple_n67(_uploadFile, _downloadFile, x));
}
function to_candid_AppUserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): _AppUserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_Community_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Community): Promise<_Community> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_Event_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): Promise<_Event> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_GalleryAlbum_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryAlbum): Promise<_GalleryAlbum> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_GalleryPhoto_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryPhoto): Promise<_GalleryPhoto> {
    return await to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_MassIntention_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MassIntention): _MassIntention {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
async function to_candid_NewsArticle_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsArticle): Promise<_NewsArticle> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PrayerStar_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrayerStar): _PrayerStar {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    order: bigint;
    blob: ExternalBlob;
    date: string;
    caption: string;
}): Promise<{
    id: string;
    order: bigint;
    blob: _ExternalBlob;
    date: string;
    caption: string;
}> {
    return {
        id: value.id,
        order: value.order,
        blob: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.blob),
        date: value.date,
        caption: value.caption
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    meetingDay: string;
    meetingPlace: string;
    caretaker: string;
    order: bigint;
    name: string;
    meetingTime: string;
    heroImage: ExternalBlob;
    shortDescription: string;
    contactEmail: string;
    fullDescription: string;
    photos: Array<ExternalBlob>;
    contactPhone: string;
}): Promise<{
    id: string;
    meetingDay: string;
    meetingPlace: string;
    caretaker: string;
    order: bigint;
    name: string;
    meetingTime: string;
    heroImage: _ExternalBlob;
    shortDescription: string;
    contactEmail: string;
    fullDescription: string;
    photos: Array<_ExternalBlob>;
    contactPhone: string;
}> {
    return {
        id: value.id,
        meetingDay: value.meetingDay,
        meetingPlace: value.meetingPlace,
        caretaker: value.caretaker,
        order: value.order,
        name: value.name,
        meetingTime: value.meetingTime,
        heroImage: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.heroImage),
        shortDescription: value.shortDescription,
        contactEmail: value.contactEmail,
        fullDescription: value.fullDescription,
        photos: await to_candid_vec_n17(_uploadFile, _downloadFile, value.photos),
        contactPhone: value.contactPhone
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    featured: boolean;
    date: string;
    published: boolean;
    description: string;
    pinned: boolean;
    liturgicalColor: string;
    image: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    featured: boolean;
    date: string;
    published: boolean;
    description: string;
    pinned: boolean;
    liturgicalColor: string;
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        date: value.date,
        published: value.published,
        description: value.description,
        pinned: value.pinned,
        liturgicalColor: value.liturgicalColor,
        image: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image)
    };
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    name: string;
    layout: string;
    description: string;
    coverImage: ExternalBlob;
    photos: Array<GalleryPhoto>;
}): Promise<{
    id: string;
    date: string;
    name: string;
    layout: string;
    description: string;
    coverImage: _ExternalBlob;
    photos: Array<_GalleryPhoto>;
}> {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        layout: value.layout,
        description: value.description,
        coverImage: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.coverImage),
        photos: await to_candid_vec_n22(_uploadFile, _downloadFile, value.photos)
    };
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    order: bigint;
    date: string;
    published: boolean;
    image: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    content: string;
    order: bigint;
    date: string;
    published: boolean;
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        order: value.order,
        date: value.date,
        published: value.published,
        image: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role?: AppUserRole;
}): {
    name: string;
    role: [] | [_AppUserRole];
} {
    return {
        name: value.name,
        role: value.role ? candid_some(to_candid_AppUserRole_n11(_uploadFile, _downloadFile, value.role)) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    assignedDayIndex?: bigint;
    name: string;
    createdAt: string;
    color: string;
    email?: string;
    assignedWeekId?: string;
    assignedEntryId?: string;
    phone?: string;
    assignedMassDate?: string;
    assignedMassTime?: string;
    offeringStatus: string;
    intention: string;
}): {
    id: string;
    status: string;
    assignedDayIndex: [] | [bigint];
    name: string;
    createdAt: string;
    color: string;
    email: [] | [string];
    assignedWeekId: [] | [string];
    assignedEntryId: [] | [string];
    phone: [] | [string];
    assignedMassDate: [] | [string];
    assignedMassTime: [] | [string];
    offeringStatus: string;
    intention: string;
} {
    return {
        id: value.id,
        status: value.status,
        assignedDayIndex: value.assignedDayIndex ? candid_some(value.assignedDayIndex) : candid_none(),
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        email: value.email ? candid_some(value.email) : candid_none(),
        assignedWeekId: value.assignedWeekId ? candid_some(value.assignedWeekId) : candid_none(),
        assignedEntryId: value.assignedEntryId ? candid_some(value.assignedEntryId) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        assignedMassDate: value.assignedMassDate ? candid_some(value.assignedMassDate) : candid_none(),
        assignedMassTime: value.assignedMassTime ? candid_some(value.assignedMassTime) : candid_none(),
        offeringStatus: value.offeringStatus,
        intention: value.intention
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isApproved: boolean;
    city?: string;
    name?: string;
    color: string;
    joinedAt: string;
    isHidden: boolean;
    isPublic: boolean;
    prayCount: bigint;
    intention?: string;
}): {
    id: string;
    isApproved: boolean;
    city: [] | [string];
    name: [] | [string];
    color: string;
    joinedAt: string;
    isHidden: boolean;
    isPublic: boolean;
    prayCount: bigint;
    intention: [] | [string];
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        city: value.city ? candid_some(value.city) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        color: value.color,
        joinedAt: value.joinedAt,
        isHidden: value.isHidden,
        isPublic: value.isPublic,
        prayCount: value.prayCount,
        intention: value.intention ? candid_some(value.intention) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): {
    admin: null;
} | {
    moderator: null;
} | {
    editor: null;
} | {
    photographer: null;
} {
    return value == AppUserRole.admin ? {
        admin: null
    } : value == AppUserRole.moderator ? {
        moderator: null
    } : value == AppUserRole.editor ? {
        editor: null
    } : value == AppUserRole.photographer ? {
        photographer: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GalleryPhoto>): Promise<Array<_GalleryPhoto>> {
    return await Promise.all(value.map(async (x)=>await to_candid_GalleryPhoto_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
